### ISSUE TITLE
How to uninstall desktopclock?

### ISSUE THREAD

**Issue by Tafrick-333** [danielchalmers/DesktopClock#35]
I cannot figure out how to uninstall desktopclock

**Comment by breem42** [comment]
Legal Disclaimer! If you blow up your computer or suddenly discover that your pet has become un-spayed as a result of following these directions, I am absolved of any responsibility for it. YMMV. Offer invalid where prohibited by law. Satisfaction guaranteed or your money cheerfully refunded.

That said. well, it depends on how you installed the program.

I'm assuming that you are using Windows 10 or 11. The info below is from my Windows 11 computer, but Windows 10 is pretty similar.

If you used the ".msi" installer, then you should be able to start the "Setup" program, then select "Apps", then find "**DesktopClock**", click on the three dots and choose "Uninstall".

Otherwise, if you just downloaded the ".exe" and started using it, try the following steps. **These directions are for people who understand what "file explorer" or ".exe" mean. If you don't understand that, you can, but this is not the place to learn it. There are plenty of places on the internet to learn. Go figure it out and come back...** 

Finally some actual information. 

1. Turn off start on boot
a) Right click on the clock. A menu will pop up
b) Make sure there is no check mark next to "**Start with PC**". If there is, click it to turn it off.

2. Exit **DesktopClock**. You have to do this before 3) will work.
a) Right click on the clock. A menu will pop up
b) Click on "Exit"

3. Delete the file
a) Start the file explorer
b) Go to the directory where you put that ".exe" file (maybe "Downloads"). If you don't know where this is, I can't help you.
c) Delete "**DesktopClock.exe**" (may be listed as simply "**DesktopClock**") If you want to to be doubly sure it is deleted, select the file then hold down Shift as you press Del.

And you're done! In general, if uninstalling this program is an issue for you, it's probably best to use the install program, so that you don't  have to go through this mess in the future.

Please let us know if this works or not.

Hey Daniel! did I get it right?

**Comment by Tafrick-333** [comment]
It seems to have worked. Thank you very much. I found another desktop clock that I like much better called DS Clock.

**Comment by danielchalmers** [comment]
Sorry to lose ya! And thank you @breem42 👏👏👏
