### ISSUE TITLE
Request: Textures

### ISSUE THREAD

**Issue by breem42** [danielchalmers/DesktopClock#36]
I think it would be great to use a tiled bitmap instead of a colour, either for the background, or especially for the actual date or time. As I use large fonts, this would work well for me. I understand that this might not be a priority for you Daniel. You may just want a simple clock that sits there doing it's job.

BTW you may not be aware of a program for Linux named [Variety](https://github.com/varietywalls/variety). It works very differently from your DesktopClock, and a desktop clock is just one of it's many functions. But it is what inspired my interest in your project.

**Comment by danielchalmers** [comment]
Hi, I added an option for a custom background image in [v4.1.0](https://github.com/danielchalmers/DesktopClock/releases/tag/v4.1.0). It's stretched to fit. I'm open to more ideas so let me know what you think and feel free to re-open the issue!

**Comment by breem42** [comment]
Thank you for your efforts.

I poked around some more. As far as I can tell there is no "TextImagePath" attribute or equivalent that would provide tile fill of the text itself. Perhaps someone has implemented some sort of extension somewhere, but I didn't find it. And thinking about it, why would they?

It looks like you can tile a background image in "[.NET MAUI](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/paint?view=net-maui-8.0)". I suspect it would require a complete re-write, since it looks like MAUI is mostly aimed at mobile developers.

**Comment by gavin1970** [comment]
Only way is to do that is paint it.   I do that but its painted on a invisible win form.  SwitchWinClock/SwitchWinClock/DisplayForm.cs at master · gavin1970/SwitchWinClockgithub.comChizlOn Jan 4, 2024, at 11:51 PM, Tony ***@***.***> wrote:﻿
Thank you for your efforts.
I poked around some more. As far as I can tell there is no "TextImagePath" attribute or equivalent that would provide tile fill of the text itself. Perhaps someone has implemented some sort of extension somewhere, but I didn't find it. And thinking about it, why would they?
It looks like you can tile a background image in ".NET MAUI". I suspect it would require a complete re-write, since it looks like MAUI is mostly aimed at mobile developers.
